# Generated by Django 6.0.3 on 2026-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentReport',
        ),
    ]
